import { customLog } from '@app/utils/util.util';
import { generateHistoricalProductionReport, generateWeeklyProductionReport } from '@services/report.service';
import { Request, Response } from 'express';

export const getWeeklyProductionReport = async (req: Request, res: Response) => {
  try {
    const user = res.locals.user;
    const { shedId } = req.params;
    const filePath = await generateWeeklyProductionReport(shedId);
    customLog(`Report generated by ${user.email} for shed ${shedId}`);
    res.download(filePath, 'weekly_production.xlsx');
  } catch (error) {
    customLog('Error generating weekly report', error);
    res.status(500).json({ message: 'Error generating weekly report', error: (error as Error).message });
  }
};

export const getHistoricalProductionReport = async (req: Request, res: Response) => {
  try {
    const user = res.locals.user;
    const { shedId } = req.params;
    const filePath = await generateHistoricalProductionReport(shedId);
    customLog(`Historical report generated by ${user.email} for shed ${shedId}`);
    res.download(filePath, 'historical_production.xlsx');
  } catch (error) {
    customLog('Error generating historical report', error);
    res.status(500).json({ message: 'Error generating historical report', error: (error as Error).message });
  }
};